name: CI for Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Run backend tests
      run: npm test
      working-directory: ./backend

    - name: Build backend
      run: npm run build
      working-directory: ./backend

  frontend-build:
    name: Frontend Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.x]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend
